name: Scott's Thoughts
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
twitter_username: @nocarsscott
description: "Scott's Blog"
title_image: "/Users/scott.smith/Documents/GitHub/PersonalBlog/scottsmith93.github.io/assets/ss.jpg"
url: "https://scottsmith93.github.io/blog/2020/07/09/environmental-factors"
